cities = {
    "AS": "Aguascalientes",
    "BS": "Baja California Sur",
    "CL": "Coahuila",
    "CS": "Chiapas",
    "DF": "Ciudad de México",
    "GT": "Guanajuato",
    "HG": "Hidalgo",
    "MC": "Mexico",
    "MS": "Morelos",
    "NL": "Nuevo Leon",
    "PL": "Puebla",
    "QR": "Quintana Roo",
    "SL": "Sinaloa",
    "TC": "Tabasco",
    "TL": "Tlaxcala",
    "YN": "Yucatan",
    "NE": "Nacido en el extranjero",
    "BC": "Baja California",
    "CC": "Campeche",
    "CM": "Colima",
    "CH": "Chihuahua",
    "DG": "Durango",
    "GR": "Guerrero",
    "JC": "Jalisco",
    "MN": "Michoacan",
    "NT": "Nayarit",
    "OC": "Oaxaca",
    "QT": "Queretaro",
    "SP": "San Luis Potosi",
    "SR": "Sonora",
    "TS": "Tamaulipas",
    "VZ": "Veracruz",
    "ZS": "Zacatecas"
}
